### ISSUE TITLE
G4 - Criar mockups de telas de Professors no Figma

### ISSUE THREAD

**Issue by eduardo-arruda** [constr-sw-2023-1/frontend#20]

**Comment by HBO1705** [comment]
- Menu lateral selecionando lista de professores
<img width="484" alt="image" src="https://github.com/constr-sw-2023-1/frontend/assets/83477377/7f9cdf3c-ce38-444c-9a44-e43701f44f80">

- Informações de professor selecionado
<img width="486" alt="image" src="https://github.com/constr-sw-2023-1/frontend/assets/83477377/59f5a0fc-27e9-4c87-bfb0-76d7e8a0594a">

- Criação/edição de professores
<img width="483" alt="image" src="https://github.com/constr-sw-2023-1/frontend/assets/83477377/fa692a3d-6f91-4025-9f59-9a6f536c661a">

-  Listar certificação
<img width="485" alt="image" src="https://github.com/constr-sw-2023-1/frontend/assets/83477377/7ad7fd02-8f98-4d7c-8aa7-54be21e30a9f">

- Criação/edição de certificações
<img width="488" alt="image" src="https://github.com/constr-sw-2023-1/frontend/assets/83477377/6dc70ef4-9d9a-4226-ab71-ddade9d23aba">
